spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookshop?serverTimezone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    view:
      suffix: .jsp
      prefix: /
mybatis:
  type-aliases-package: com.bean
  mapper-locations: classpath:mapper/*.xml
